---
- hosts: all
  roles:
    - { role: setup/validate-host, tags: base-system }
    - { role: setup/base-system, tags: base-system }

- hosts: all
  roles:
    - { role: bennojoy.mysql, tags: database,
        sudo: yes,
        mysql_root_db_pass: '',
        mysql_db: [{ name: beaker }, { name: beaker_test }, { name: beaker_migration_test }],
        mysql_users: [{ name: beaker, pass: beaker, priv: "beaker.*:ALL" }]
      }
    - { role: beaker/setup/repos, tags: beaker }
    - { role: beaker/setup/packages, tags: beaker }
    - { role: beaker/setup/db, tags: [beaker, database],
        mysql_users: [{ name: beaker, priv: "beaker_test.*:ALL" },
                      { name: beaker, priv: "beaker_migration_test.*:ALL" }]
      }
  tasks:
    - debug: msg="Setup successfull, Enjoy!"
