---
- hosts: all
  roles:
    - { role: setup/validate-host, tags: base-system }
    - { role: setup/base-system, tags: base-system }

- hosts: all
  roles:
    - { role: geerlingguy.mysql, tags: database,
        sudo: yes,
        mysql_root_password: '',
        mysql_databases: [{ name: beaker }, { name: beaker_test }, { name: beaker_migration_test }],
        mysql_users: [{ name: beaker, password: beaker, priv: "beaker.*:ALL" }]
      }
    - { role: beaker/setup/repos, tags: beaker }
    - { role: beaker/setup/packages, tags: beaker }
  tasks:
    - debug: msg="Setup successfull, Enjoy!"
