---
- name: Ensure we can access init script
  stat:
    path: /workspace/Server/bkr/server/tools/init.py
  register: beaker_init
    
- name: Run init
  command: python bkr/server/tools/init.py --user={{ user }} --password={{ password }} --email={{ email }}
  args:
    chdir: /workspace/Server
  environment:
    PYTHONPATH: "../Common:."