devbase:
  build: base/CentOS6

dev:
  build: dev

sandbox:
  image: beaker_dev
  working_dir: /home/dev
  user: dev
  privileged: true
  volumes:
    - ../../beaker:/home/dev/beaker
    - /tmp/beaker_mysql:/var/lib/mysql/
  ports:
    - "8080:8080"
